version: '3.8'

services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/backend
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: kidsbpep
      POSTGRES_PASSWORD: Da_X0HObSCVPd9uHyG9RA--JVubROEar
      POSTGRES_DB: kidsbpep
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
