version: "3.8"
services:
  cognied_backend:
    build: .
    command: gunicorn cognied.wsgi --bind 0.0.0.0:8002 --workers 10
    environment:
      TZ: America/Bogota
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - .:/backend
    ports:
      - 8002:8002

  cognied_frontend:
    build: ../front-cognied
    environment:
      TZ: America/Bogota
      CHOKIDAR_USEPOLLING: "true"
    volumes:   
      - ../front-cognied:/frontend
      - ../front-cognied/build:/usr/share/nginx/html
      - ./static:/static
      - ../front-cognied/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:8888
    depends_on:
      - cognied_backend
