# Generated by Django 4.0.1 on 2022-05-13 01:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPreguntaRespuesta',
            fields=[
                ('id_survey', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('desc', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=30)),
                ('id_question', models.IntegerField()),
                ('itemid_question', models.IntegerField(blank=True, db_column='itemID_question', null=True)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=60)),
                ('id_answer', models.IntegerField()),
                ('order_answer', models.IntegerField()),
            ],
            options={
                'db_table': 'view_pregunta_respuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewRespuestaEncuestas',
            fields=[
                ('id_encuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('encuesta', models.CharField(max_length=45)),
                ('id_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(blank=True, max_length=40, null=True)),
                ('id_pregunta', models.IntegerField()),
                ('pregunta', models.TextField()),
                ('id_respuesta', models.IntegerField()),
                ('respuesta', models.CharField(max_length=60)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_respuesta_encuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Definiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion', models.TextField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('colorhex', models.CharField(db_column='colorHex', max_length=30)),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escolaridad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('funcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
            ],
            options={
                'ordering': ('-creado',),
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('itemid', models.IntegerField(blank=True, db_column='itemID', null=True)),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.encuesta')),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='PreguntaRespuesta',
            fields=[
                ('id_pregunta_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.pregunta')),
            ],
            options={
                'db_table': 'pregunta_respuesta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('respuesta', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='SeccionEmocional',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=40, null=True)),
                ('capsula1', models.BooleanField(default=False)),
                ('capsula2', models.BooleanField(default=True)),
                ('actividad1', models.BooleanField(default=True)),
                ('capsula3', models.BooleanField(default=True)),
                ('actividad2', models.BooleanField(default=True)),
                ('capsula4', models.BooleanField(default=True)),
                ('actividad3', models.BooleanField(default=True)),
                ('capsula5', models.BooleanField(default=True)),
                ('capsula6', models.BooleanField(default=True)),
                ('actividad4', models.BooleanField(default=True)),
                ('capsula7', models.BooleanField(default=True)),
                ('capsula8', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEncuesta',
            fields=[
                ('id_usuario_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.encuesta')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_encuesta',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRespuesta',
            fields=[
                ('id_usuario_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('id_pregunta_respuesta', models.ForeignKey(db_column='id_pregunta_respuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.preguntarespuesta')),
                ('id_usuario_encuesta', models.ForeignKey(db_column='id_usuario_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuarioencuesta')),
            ],
            options={
                'db_table': 'usuario_respuesta',
            },
        ),
        migrations.AddField(
            model_name='preguntarespuesta',
            name='id_respuesta',
            field=models.ForeignKey(db_column='id_respuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.respuesta'),
        ),
        migrations.CreateModel(
            name='DefinicionesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('definicion_usuario', models.TextField()),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.definiciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='emociones',
            field=models.ManyToManyField(to='api.Emocion'),
        ),
    ]
