# Generated by Django 4.0.1 on 2022-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRespuestaEncuestas',
            fields=[
                ('id_encuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('encuesta', models.CharField(db_collation='utf8_general_ci', max_length=45)),
                ('id_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=40, null=True)),
                ('id_pregunta', models.IntegerField()),
                ('pregunta', models.TextField(db_collation='utf8_general_ci')),
                ('id_respuesta', models.IntegerField()),
                ('respuesta', models.CharField(db_collation='utf8_general_ci', max_length=60)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_respuesta_encuestas',
                'managed': False,
            },
        ),
    ]
