# Generated by Django 4.0.1 on 2022-05-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacion',
            name='emociones',
        ),
        migrations.AddField(
            model_name='emocion',
            name='clasificacion',
            field=models.ManyToManyField(to='api.Clasificacion'),
        ),
    ]
