# Generated by Django 4.0.1 on 2022-01-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('PA', 'PA'), ('CE', 'CE'), ('CC', 'CC'), ('TI', 'TI'), ('RC', 'RC')], default='CC', max_length=2)),
                ('documento', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='slug',
        ),
    ]
