# Generated by Django 4.0 on 2022-06-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancemodulos',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='authentication.usuarios'),
        ),
        migrations.AlterUniqueTogether(
            name='definicionesusuario',
            unique_together={('definicion', 'usuario')},
        ),
    ]
