# Generated by Django 4.0.1 on 2022-05-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_clasificacion_emociones_emocion_clasificacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='definicionesusuario',
            unique_together={('definicion', 'usuario')},
        ),
    ]
