# Generated by Django 4.0.1 on 2022-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_viewrespuestaencuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionEmocional',
            fields=[
                ('id_seccion', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=40, null=True)),
                ('capsula1', models.BooleanField(default=True)),
                ('capsula2', models.BooleanField(default=False)),
                ('actividad1', models.BooleanField(default=False)),
                ('capsula3', models.BooleanField(default=False)),
                ('actividad2', models.BooleanField(default=False)),
                ('capsula4', models.BooleanField(default=False)),
                ('actividad3', models.BooleanField(default=False)),
                ('capsula5', models.BooleanField(default=False)),
                ('capsula6', models.BooleanField(default=False)),
                ('actividad4', models.BooleanField(default=False)),
                ('capsula7', models.BooleanField(default=False)),
                ('capsula8', models.BooleanField(default=False)),
            ],
        ),
    ]
