# Generated by Django 4.0 on 2022-06-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_lugar_nacimiento_usuarios_ciudad_nacimiento_and_more'),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewPreguntaRespuesta',
        ),
        migrations.DeleteModel(
            name='ViewRespuestaEncuestas',
        ),
        migrations.AlterField(
            model_name='definicionesusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarioencuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioencuesta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.usuarios'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
