# Generated by Django 4.0.1 on 2022-01-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datos_remove_personal_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escolaridad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='datos',
            name='ciudad_residencia',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='estrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='lugar_nacimiento',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='ocupacion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='documento',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('PA', 'PA'), ('CE', 'CE'), ('CC', 'CÉDULA DE CIUDADANÍA'), ('TI', 'TI'), ('RC', 'RC')], default='CC', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='escolaridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.escolaridad'),
        ),
        migrations.AddField(
            model_name='datos',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado_civil'),
        ),
        migrations.AddField(
            model_name='datos',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexo'),
        ),
    ]
