# Generated by Django 4.0 on 2022-06-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_viewpreguntarespuesta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeccionEmocional',
        ),
    ]
