# Generated by Django 4.0 on 2022-06-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0003_alter_definicionesusuario_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocional', models.IntegerField(default=1)),
                ('estres', models.IntegerField(default=1)),
                ('diagnostico', models.IntegerField(default=1)),
                ('cognitivo', models.IntegerField(default=1)),
                ('habilidades', models.IntegerField(default=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='authentication.usuarios')),
            ],
        ),
    ]
