# Generated by Django 4.0.1 on 2022-02-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_datos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='datos',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
