# Generated by Django 4.0 on 2022-06-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0004_avancemodulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancemodulos',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='authentication.usuarios'),
        ),
    ]
