# Generated by Django 4.0.1 on 2022-04-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_seccionemocional_id_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionemocional',
            name='actividad1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='actividad2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='actividad3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='actividad4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula5',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula6',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula7',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionemocional',
            name='capsula8',
            field=models.BooleanField(default=True),
        ),
    ]
