# Generated by Django 4.0 on 2022-07-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_seccionemocional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avancemodulos',
            old_name='diagnostico',
            new_name='autoevaluativo',
        ),
    ]
