# Generated by Django 4.0.1 on 2022-02-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_datos_actualizado_datos_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=400)),
                ('tipo_documento', models.CharField(blank=True, choices=[('PA', 'PA'), ('CE', 'CE'), ('CC', 'CÉDULA DE CIUDADANÍA'), ('TI', 'TI'), ('RC', 'RC')], default='CC', max_length=2, null=True)),
                ('documento', models.BigIntegerField(blank=True, null=True)),
                ('lugar_nacimiento', models.TextField(blank=True, max_length=200, null=True)),
                ('ocupacion', models.TextField(blank=True, max_length=200, null=True)),
                ('ciudad_residencia', models.TextField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estrato', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.escolaridad')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado_civil')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexo')),
            ],
        ),
        migrations.RemoveField(
            model_name='datos',
            name='escolaridad',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='sexo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
    ]
