# Generated by Django 4.0 on 2022-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_programaacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancemodulos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
