# Generated by Django 4.0.1 on 2022-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuarios_documento_alter_usuarios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
