# Generated by Django 4.0.1 on 2022-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usuarios_nombre_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.TextField(max_length=200),
        ),
    ]
