# Generated by Django 4.0.1 on 2022-02-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usuarios_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='documento',
            field=models.BigIntegerField(unique=True),
        ),
    ]
