# Generated by Django 4.0.1 on 2022-02-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuarios_options_alter_usuarios_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
