# Generated by Django 4.0 on 2022-06-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('tipo_documento', models.CharField(choices=[('PA', 'PA'), ('CE', 'CÉDULA DE EXTRANJERÍA'), ('CC', 'CÉDULA DE CIUDADANÍA'), ('TI', 'TARJETA DE IDENTIDAD'), ('RC', 'REGISTRO CIVIL')], default='CC', max_length=2)),
                ('lugar_nacimiento', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('password', models.CharField(max_length=100)),
                ('programa', models.CharField(max_length=200)),
                ('semestre', models.IntegerField()),
                ('covid_positivo', models.BooleanField()),
                ('covid_familiar', models.BooleanField()),
                ('covid_vacuna', models.BooleanField()),
                ('covid_dosis', models.BooleanField(blank=True, null=True)),
                ('discapacidad', models.BooleanField()),
                ('covid_tipo_vacuna', models.CharField(blank=True, choices=[('A', 'Auditiva'), ('V', 'Visual'), ('S', 'Sordoceguera'), ('I', 'Intelectual'), ('P', 'Psicosocial (mental)'), ('M', 'Múltiple')], max_length=1, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telefono', models.BigIntegerField()),
                ('ocupacion', models.CharField(max_length=200)),
                ('is_controlgroup', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado_civil')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexo')),
            ],
        ),
    ]
