# Generated by Django 4.0 on 2022-06-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='covid_dosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='covid_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='covid_positivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='covid_vacuna',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='discapacidad',
            field=models.BooleanField(default=False),
        ),
    ]
