# Generated by Django 4.0.1 on 2022-02-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='document',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
