# Generated by Django 4.0.1 on 2022-04-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escolaridad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='escolaridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.escolaridad'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.estado_civil'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.sexo'),
        ),
    ]
