# Generated by Django 4.0 on 2022-06-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usuarios_covid_dosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='lugar_nacimiento',
            new_name='ciudad_nacimiento',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='departamento_nacimiento',
            field=models.CharField(default='Nunca Jamás', max_length=200),
            preserve_default=False,
        ),
    ]
