# Generated by Django 4.0 on 2022-07-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_programaacademico'),
        ('authentication', '0003_rename_lugar_nacimiento_usuarios_ciudad_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='programa_academico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programaacademico'),
        ),
    ]
